%%%
%%% createRunScript.m
%%%
%%% Convenience function to create a run script for the MAMEBUS code.
%%%
%%% local_home_dir - Directory in which to put the run on the local system
%%% run_name - Name for the folder containing the run files
%%% exec_name - Name of the MAMEBUS executable
%%% use_cluster - Set true to set up scripts to run on a remote cluster
%%% cluster_username - User login name for the cluster
%%% cluster_address - Cluster DNS identifier (e.g. stampede.tacc.xsede.org)
%%% cluster_home_dir - Directory into which the run directory should be
%%%                    copied on the remote cluster
%%% walltime - Max. execution time on the remote cluster
%%% 
%%% 
%%%
function createRunScript (local_home_dir,run_name,exec_name, ...
                          use_cluster,cluster_username,cluster_address, ...
                          cluster_home_dir,walltime)

  %%% File/directory names      
  local_run_dir = fullfile(local_home_dir,run_name);
  pbsfname = fullfile(local_run_dir,'pbs_run');
  upfname = fullfile(local_run_dir,'upload.sh');
  downfname = fullfile(local_run_dir,'download.sh');
  cleanfname = fullfile(local_run_dir,'clean.sh');
  sfname = fullfile(local_run_dir,'run.sh');
  
  %%% Copy code files over
  if (~copyfile('../code/*',local_run_dir))
    error(['Could not copy code files to ',local_run_dir]);
  end
  
  %%% Create a script file to run the code
  sfid = fopen(sfname,'w');
  if (sfid == -1)
    error(['Could not open ',sfname]);
  end    
  run_str = ['./',strtrim(exec_name),' ',run_name,'_in ','.\n']; 
    
  %%% If we're using the cluster, create a PBS run script
  if (use_cluster)     
  
    %%% TODO this needs to be edited
    pbsstr = strcat( ...
      '#!/bin/bash -f\n', ...
      '#PBS -l nodes=1 \n', ...
      '#PBS -l walltime=',num2str(round(walltime)),':00:00 \n', ...
      '#PBS -N\t ',run_name,'\n', ...
      '#PBS -o ./out.$PBS_JOBID \n', ...
      '#PBS -e ./err.$PBS_JOBID \n', ...
      '#PBS -S /bin/bash \n', ...
      '#PBS -V \n', ...
      '#PBS -q shared \n', ...
      '#PBS -m ae \n', ...     
      '\n', ...
      'source /etc/profile.d/modules.sh\n', ...
      '\n', ...
      'module load intel/intel-12\n', ...
      '\n', ...
      'echo "MPI Used:"  `which mpirun`\n', ...
      '\n', ...
      '#change the working directory (default is home directory)\n', ...
      'echo Working directory is $PBS_O_WORKDIR\n', ...
      'cd $PBS_O_WORKDIR\n', ...
      '\n', ...
      '# Write out some information on the job\n', ...
      'echo Running on host `hostname`\n', ...
      'echo Time is `date`\n', ...
      '\n', ...
      '###### Define number of processors\n', ...
      'NPROCS=`wc -l < $PBS_NODEFILE`\n', ...
      'echo This job has allocated $NPROCS cpus\n', ...
      '\n', ...
      '# Tell me which nodes it is run on\n', ...
      'echo " "\n', ...
      'echo This job runs on the following processors:\n', ...
      'echo `cat $PBS_NODEFILE`\n', ...
      'echo " "\n', ...
      '\n', ...
      '#\n', ...
      '# Run the job\n', ...
      '#\n', ...
      '\n', ...
      '# Setup regcache for MX\n', ...
      '\n', ...
      'export MX_RCACHE=0\n', ...
      '\n', ...
      run_str,'\n' );
    
    %%% Run.sh just executes the PBS script    
    fprintf(sfid,['qsub ',pbsfname,' > output.txt']);
    
    %%% Create the PBS run script
    pbsfid = fopen(pbsfname,'w');
    if (pbsfid == -1)
      error(['Could not open ',pbsfname]);
    end
    fprintf(pbsfid,pbsstr);
    fclose(pbsfid);
    
    %%% Create a file to upload the run to the cluster    
    upstr = ['scp -r ',fullfile('..',run_name),' ',strtrim(cluster_username),'@',strtrim(cluster_address),':',strtrim(cluster_home_dir)];
    upfid = fopen(upfname,'w');
    if (upfid == -1)
      error(['Could not open ',upfname]);
    end
    fprintf(upfid,upstr);
    fclose(upfid);
    
    %%% Create a file to download the run from the cluster
    downstr = ['scp -r ',strtrim(cluster_username),'@',strtrim(cluster_address),':',strtrim(cluster_home_dir),'/',strtrim(run_name),' ../'];
    downfid = fopen(downfname,'w');
    if (downfid == -1)
      error(['Could not open ',downfname]);
    end
    fprintf(downfid,downstr);
    fclose(downfid);

  %%% Otherwise just create a script to run locally
  else
             
    fprintf(sfid,run_str);

  end
  
  %%% Create a file to clean the run folder of output files
  cleanstr = 'for f in ./*n=*.dat; do rm $f; done';
  cleanfid = fopen(cleanfname,'w');
  if (cleanfid == -1)
    error(['Could not open ',cleanfname]);
  end
  fprintf(cleanfid,cleanstr);
  fclose(cleanfid);

  %%% Close run script
  fclose(sfid);  
  
end


